name: river_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  random_name_generator: ^1.2.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
